"""Explanation generation agent."""

import logging

from app.ai.state import GraphState

logger = logging.getLogger(__name__)


def explanation_generation_node(state: GraphState) -> GraphState:
    """Generate human-readable explanations for candidate matches.
    
    This is a stub implementation that logs execution.
    """
    logger.info("Executing Explanation_Generation_Agent node")
    
    candidate_scores = state.get("candidate_scores")
    if not candidate_scores:
        logger.warning("No candidate_scores found in state")
        return state
    
    # Stub: Explanations are generated by Result_Aggregation_Agent in this stub
    logger.info(f"Explanation_Generation_Agent completed for {len(candidate_scores)} candidates")
    return state
