BEGIN;

-- =========================================================
-- TABLE: auth_clients
-- =========================================================
CREATE TABLE auth_clients (
    id SMALLINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    client_name VARCHAR(100) NOT NULL,
    client_code VARCHAR(50) NOT NULL UNIQUE,
	client_secret_hash VARCHAR(255) NOT NULL,
    auth_type VARCHAR(10) NOT NULL DEFAULT 'OAUTH'
        CHECK (auth_type IN ('OAUTH','API_KEY','SAML')),
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

INSERT INTO auth_clients (client_name, client_code, client_secret_hash, auth_type, is_active, created_at)
VALUES
('InfoBeans Talent Acquisition', 'INFOBEANS_TA', 'client-generated-256-bit-secret','OAUTH', TRUE, '2026-01-12 16:52:07');


-- =========================================================
-- TABLE: auth_access_tokens
-- =========================================================
CREATE TABLE auth_access_tokens (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    auth_client_id SMALLINT NOT NULL,
    access_token VARCHAR(255) NOT NULL UNIQUE,
    expires_at TIMESTAMP NOT NULL,
    is_revoked BOOLEAN NOT NULL DEFAULT FALSE,
    issued_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_token_client
        FOREIGN KEY (auth_client_id)
        REFERENCES auth_clients (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_token_client ON auth_access_tokens(auth_client_id);
CREATE INDEX idx_token_expiry ON auth_access_tokens(expires_at);


-- =========================================================
-- TABLE: requisition_status_master
-- =========================================================
CREATE TABLE requisition_status_master (
    status_id SMALLINT PRIMARY KEY,
    status_key VARCHAR(40) NOT NULL UNIQUE,
    status_message VARCHAR(255) NOT NULL
);

INSERT INTO requisition_status_master VALUES
(100, 'RECEIVED', 'Request accepted'),
(101, 'VALIDATED', 'Validation successful'),
(102, 'MATCHING_INITIATED', 'Matching initiated'),
(103, 'MATCHING_IN_PROGRESS', 'Matching running'),
(104, 'MATCHING_COMPLETED', 'Matching completed'),
(105, 'FAILED', 'Processing failed'),
(106, 'INVALID_JD', 'Invalid or incomplete JD');



-- =========================================================
-- TABLE: requisition_requests
-- =========================================================
CREATE TABLE requisition_requests (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL UNIQUE,
    auth_client_id SMALLINT NOT NULL,
    status SMALLINT NOT NULL,
    client_name VARCHAR(100) NOT NULL,
    correlation_id VARCHAR(100),
    received_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    completed_at TIMESTAMP,

    CONSTRAINT fk_req_auth_client
        FOREIGN KEY (auth_client_id)
        REFERENCES auth_clients (id),

    CONSTRAINT fk_req_status
        FOREIGN KEY (status)
        REFERENCES requisition_status_master (status_id)
);

CREATE INDEX idx_req_status ON requisition_requests(status);
CREATE INDEX idx_received_at ON requisition_requests(received_at);

INSERT INTO requisition_requests
(request_id, auth_client_id, status, client_name, correlation_id, received_at, completed_at)
VALUES
('REQ-2026-000145', 1, 104, 'InfoBeans', 'CORR-9987123', '2026-01-12 16:52:07', NULL);


-- =========================================================
-- TABLE: requisition_detail
-- =========================================================
CREATE TABLE requisition_detail (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    requisition_request_id INT NOT NULL UNIQUE,
    payload_json JSONB NOT NULL,
    payload_hash CHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	CONSTRAINT uk_payload_hash UNIQUE (payload_hash),
    CONSTRAINT fk_req_detail_request
        FOREIGN KEY (requisition_request_id)
        REFERENCES requisition_requests (id)
        ON DELETE CASCADE
);

CREATE INDEX idx_payload_hash ON requisition_detail(payload_hash);

INSERT INTO requisition_detail
(requisition_request_id, payload_json, payload_hash, created_at)
VALUES
(
  1,
  '{
  "metadata": {
    "request_id": "REQ-2026-000145",
    "api_version": "1.1",
    "source_system": "EAGLE_v1"
    },
  "job_description": {
    "client_name": "DNC",
    "title": "Senior Backend Engineer",
    "role": "Backend Engineer",
    "requisition_duration_month": 3,
    "expected_start_date": "2026-02-15",
    "priority": "HIGH",
    "location": ["Bangalore","Pune"],
	"work_mode":["wfo","wfh"],
    "experience": {
      "min_months": 96,
      "max_months": 120
    },
    "mandatory_skills": [
      "Python",
      "Django",
      "REST API",
      "AWS",
      "PostgreSQL"
    ],
    "preferred_skills": [
      "Docker",
      "Kubernetes"
    ],
    "jd_text": "Looking for a Senior Backend Engineer with strong backend experience in Python, Django, REST APIs, AWS, and PostgreSQL."
  }
}',
  '767ec4af49899905caad8211d13464c4900eb4cf3852cb3f8f3555da4fa502b7',
  '2026-01-12 16:52:08'
);

-- payload_hash: SHA256 Hash	

CREATE TABLE category_master (
    category_id SMALLINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    category_name          VARCHAR(100) NOT NULL,
    created_at          TIMESTAMP DEFAULT now(),
    UNIQUE (category_name)
);

CREATE TABLE skill_master (
    skill_id            VARCHAR(50) PRIMARY KEY,
    skill_name          VARCHAR(100) NOT NULL,
    category_id SMALLINT NOT NULL,
    created_at          TIMESTAMP DEFAULT now(),
    UNIQUE (skill_name),
    CONSTRAINT fk_category
		FOREIGN KEY (category_id)
		REFERENCES category_master (category_id)
		ON DELETE CASCADE
);


CREATE TYPE work_type_enum AS ENUM (
    'wfo',
    'wfh',
    'hybrid'
);

CREATE TABLE team_member (
    team_member_id          VARCHAR(50) PRIMARY KEY,
    designation             VARCHAR(100),
    profile_type            VARCHAR(50),
	is_active      			BOOLEAN DEFAULT true,
    experience_in_months    INTEGER,
    base_location           VARCHAR(100),
    work_type work_type_enum,
    profile_url             VARCHAR(1024),
    created_at              TIMESTAMP DEFAULT now()
);

CREATE TABLE team_member_allocation (
    team_member_id          VARCHAR(50) REFERENCES team_member(team_member_id),
    project_id              VARCHAR(50),
    allocation_percentage   NUMERIC(5,2),
    start_date              DATE,
    end_date                DATE,
    billable                BOOLEAN,
    is_deleted              BOOLEAN DEFAULT false,
	
    PRIMARY KEY (team_member_id, project_id)
);
CREATE INDEX idx_allocation_member
ON team_member_allocation(team_member_id);

CREATE TABLE team_member_skill (
    team_member_id      VARCHAR(50) REFERENCES team_member(team_member_id),
    skill_id            VARCHAR(50) REFERENCES skill_master(skill_id),
    rating              INTEGER,
    experience_in_months    INTEGER,
    is_deleted          BOOLEAN DEFAULT false,
	PRIMARY KEY (team_member_id, skill_id)
);

CREATE INDEX idx_team_member_skill_skill
ON team_member_skill(skill_id);

CREATE TABLE team_member_skill_certification (
    id INT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    certification_id    VARCHAR(100),
    team_member_id      VARCHAR(50)  NOT NULL,
    skill_id            VARCHAR(50)  NOT NULL,
    certificate   		VARCHAR(150),
    issuer              VARCHAR(100),
    issued_date         DATE,
    valid_till          DATE,
    FOREIGN KEY (team_member_id, skill_id)
        REFERENCES team_member_skill(team_member_id, skill_id)
);

-- =========================================================
-- TABLE: langgraph_checkpoints
-- =========================================================
CREATE TABLE langgraph_checkpoints (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    request_id VARCHAR(64) NOT NULL,
    node_name VARCHAR(50) NOT NULL,
    state_json JSONB NOT NULL,
	token_count INT,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,

    CONSTRAINT fk_lg_checkpoint_request
        FOREIGN KEY (request_id)
        REFERENCES requisition_requests (request_id)
        ON DELETE CASCADE ON UPDATE CASCADE
);

CREATE INDEX idx_req_node ON langgraph_checkpoints(request_id, node_name);
CREATE INDEX idx_lg_created_at ON langgraph_checkpoints(created_at);

COMMIT;