"""Cleanup script for test data generated by generate_test_data.py.

Removes test data based on ID patterns or metadata flags.

Usage:
    # Delete by ID pattern (recommended)
    python scripts/cleanup_test_data.py --pattern "TM%06%" --type team_members
    
    # Delete by metadata flag
    python scripts/cleanup_test_data.py --metadata scale_test --database postgresql://user:pass@localhost/db
    
    # Dry run (preview what will be deleted)
    python scripts/cleanup_test_data.py --pattern "REQ%06%" --type requisitions --dry-run
"""

import argparse
import sys
from pathlib import Path

# Add project root to path
sys.path.insert(0, str(Path(__file__).parent.parent / "src"))


def cleanup_by_pattern(conn, table: str, id_column: str, pattern: str, dry_run: bool = False):
    """Delete records matching ID pattern."""
    from sqlalchemy import text
    
    # Count records
    count_query = f"SELECT COUNT(*) FROM {table} WHERE {id_column} LIKE :pattern"
    result = conn.execute(text(count_query), {"pattern": pattern})
    count = result.scalar()
    
    print(f"\nFound {count} records in {table} matching pattern '{pattern}'")
    
    if count == 0:
        return 0
    
    if dry_run:
        print(f"[DRY RUN] Would delete {count} records from {table}")
        return count
    
    # Confirm deletion
    if count > 100:
        response = input(f"⚠️  Delete {count} records from {table}? (yes/no): ")
        if response.lower() != "yes":
            print("Aborted.")
            return 0
    
    # Delete records
    delete_query = f"DELETE FROM {table} WHERE {id_column} LIKE :pattern"
    conn.execute(text(delete_query), {"pattern": pattern})
    conn.commit()
    
    print(f"✅ Deleted {count} records from {table}")
    return count


def cleanup_by_metadata(conn, pattern: str, dry_run: bool = False):
    """Delete records with specific metadata flag."""
    from sqlalchemy import text
    
    # Count requisitions with metadata flag
    count_query = """
        SELECT COUNT(*) FROM requisition_requests 
        WHERE metadata::jsonb @> :metadata::jsonb
    """
    result = conn.execute(text(count_query), {"metadata": f'{{"{pattern}": true}}'})
    count = result.scalar()
    
    print(f"\nFound {count} requisitions with metadata.{pattern}=true")
    
    if count == 0:
        return 0
    
    if dry_run:
        print(f"[DRY RUN] Would delete {count} requisitions")
        return count
    
    # Confirm deletion
    if count > 100:
        response = input(f"⚠️  Delete {count} requisitions? (yes/no): ")
        if response.lower() != "yes":
            print("Aborted.")
            return 0
    
    # Delete records
    delete_query = """
        DELETE FROM requisition_requests 
        WHERE metadata::jsonb @> :metadata::jsonb
    """
    conn.execute(text(delete_query), {"metadata": f'{{"{pattern}": true}}'})
    conn.commit()
    
    print(f"✅ Deleted {count} requisitions")
    return count


def main():
    parser = argparse.ArgumentParser(description="Cleanup test data")
    parser.add_argument("--database", type=str, required=True, help="Database connection string")
    parser.add_argument("--pattern", type=str, help="ID pattern to match (e.g., 'TM%%' for test members)")
    parser.add_argument("--type", type=str, 
                       choices=["team_members", "allocations", "requisitions", "all"],
                       help="Type of records to delete")
    parser.add_argument("--metadata", type=str, help="Metadata flag to match (e.g., 'scale_test')")
    parser.add_argument("--dry-run", action="store_true", help="Preview what will be deleted without deleting")
    
    args = parser.parse_args()
    
    if not args.pattern and not args.metadata:
        print("❌ Error: Must specify either --pattern or --metadata")
        sys.exit(1)
    
    try:
        from sqlalchemy import create_engine
        
        print(f"Connecting to database...")
        engine = create_engine(args.database)
        
        with engine.connect() as conn:
            total_deleted = 0
            
            if args.metadata:
                # Cleanup by metadata
                total_deleted += cleanup_by_metadata(conn, args.metadata, args.dry_run)
            
            elif args.pattern:
                # Cleanup by ID pattern
                if args.type == "team_members" or args.type == "all":
                    total_deleted += cleanup_by_pattern(
                        conn, "team_members", "team_member_id", args.pattern, args.dry_run
                    )
                
                if args.type == "allocations" or args.type == "all":
                    # Find allocations for deleted members
                    alloc_pattern = args.pattern if "ALLOC" in args.pattern else f"TM{args.pattern[2:]}"
                    total_deleted += cleanup_by_pattern(
                        conn, "team_member_allocations", "team_member_id", alloc_pattern, args.dry_run
                    )
                
                if args.type == "requisitions" or args.type == "all":
                    req_pattern = args.pattern if "REQ" in args.pattern else f"REQ{args.pattern[2:]}"
                    total_deleted += cleanup_by_pattern(
                        conn, "requisition_requests", "request_id", req_pattern, args.dry_run
                    )
            
            if args.dry_run:
                print(f"\n[DRY RUN] Would delete {total_deleted} total records")
            else:
                print(f"\n✅ Cleanup complete! Deleted {total_deleted} total records")
    
    except ImportError:
        print("❌ Error: sqlalchemy not installed. Install with: pip install sqlalchemy psycopg2-binary")
        sys.exit(1)
    except Exception as e:
        print(f"❌ Error: {e}")
        sys.exit(1)


if __name__ == "__main__":
    main()
